version: '3'
services:
  echo:
    image: echo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cmd: echo
    expose:
      - 9000
    environment:
      GRPC_SERVER_PORT: 9000
    networks: 
      - mesh
  ok:
    image: client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cmd: client
    environment:
      GRPC_SERVER_ADDRESS: envoy:80
    networks:
      - mesh
  envoy:
    image: envoyproxy/envoy:v1.13.1
    command: /usr/local/bin/envoy -c /etc/server-envoy-proxy.yaml -l error --service-cluster backend-proxy
    volumes:
      - ./envoy-proxy.yaml:/etc/server-envoy-proxy.yaml
    expose:
      - 80
      - 8001
    ports:
      - 8000:80
      - 8001:8001
    networks:
      - mesh
networks:
  mesh: {}
